version: "3.9"
services:

  django-app:
    container_name: app-container
    build:
      context: .
    ports: 
      - 8000:8000
    volumes: 
      - .:/app
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings

    depends_on:
      - db
    
  db:
    container_name: db-container
    image: postgres:alpine3.18
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - '5432:5432'
    volumes:
      - dev-db-data:/var/lib/postgresql/data
  
volumes:
  dev-db-data:
